// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: CTResponse.proto

package customer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CTResponse) Reset() {
	*x = CTResponse{}
	mi := &file_CTResponse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTResponse) ProtoMessage() {}

func (x *CTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CTResponse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTResponse.ProtoReflect.Descriptor instead.
func (*CTResponse) Descriptor() ([]byte, []int) {
	return file_CTResponse_proto_rawDescGZIP(), []int{0}
}

func (x *CTResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CTResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_CTResponse_proto protoreflect.FileDescriptor

const file_CTResponse_proto_rawDesc = "" +
	"\n" +
	"\x10CTResponse.proto\x12\bcustomer\">\n" +
	"\n" +
	"CTResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06resultB\x1cZ\x1ainternal/pkg/grpc/customerb\x06proto3"

var (
	file_CTResponse_proto_rawDescOnce sync.Once
	file_CTResponse_proto_rawDescData []byte
)

func file_CTResponse_proto_rawDescGZIP() []byte {
	file_CTResponse_proto_rawDescOnce.Do(func() {
		file_CTResponse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CTResponse_proto_rawDesc), len(file_CTResponse_proto_rawDesc)))
	})
	return file_CTResponse_proto_rawDescData
}

var file_CTResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CTResponse_proto_goTypes = []any{
	(*CTResponse)(nil), // 0: customer.CTResponse
}
var file_CTResponse_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CTResponse_proto_init() }
func file_CTResponse_proto_init() {
	if File_CTResponse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CTResponse_proto_rawDesc), len(file_CTResponse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CTResponse_proto_goTypes,
		DependencyIndexes: file_CTResponse_proto_depIdxs,
		MessageInfos:      file_CTResponse_proto_msgTypes,
	}.Build()
	File_CTResponse_proto = out.File
	file_CTResponse_proto_goTypes = nil
	file_CTResponse_proto_depIdxs = nil
}
